### ISSUE TITLE
kat planlarının eklenmesi

### ISSUE THREAD

**Issue by alierisir** [IYB-IZMIR-UCLUSU/FEDERATED#3]
Yapacağımız projeye ait kat planlarını ekler misin, MT2-3 binası _5._**6.7.8.**_9._

**Comment by u2un3ray** [comment]
CAD Dosyaları adında klasör ile paylaşıldı.

**Comment by alierisir** [comment]
pull request açmayı unuttun sanırım sadece senin forkta var dosyalar

**Comment by alierisir** [comment]
senin lokal depondan (forktan) çektim. Issue kapanmıştır.

**Comment by u2un3ray** [comment]
Evet emin olamadım pull request ten tamamdır
